import type { Metadata } from "next";

import "./globals.css";
import Provider from "./lib/Provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body suppressHydrationWarning={true} className={`antialiased`}>
        <Provider>
          <div className=" max-w-[1400px] mx-auto">{children}</div>
        </Provider>
      </body>
    </html>
  );
}
